[TCID-DIR-DMAAS-CSTOR-NON-RESTIC] Dmaas non restic
mayadata-io/oep-e2e-aws pull request #49
Opened 2020-06-25 12:39 UTC by rohan2794

- Dmaas backup of minio application using block based
- Artifacts expiry time set to one week
- Deleting minio application pods when tests executed successfully

2020-06-25 12:49 UTC, amitbhatt818 requested changes

2020-06-25 12:49 UTC, amitbhatt818 commented on stages/14-director-gui-check/template/create-spc-pool.yaml
> +    - dummyvalue
The blockdevice here should not be of master node @rohan2794

2020-06-25 15:22 UTC, harshshekhar15 approved these changes

2020-06-26 07:13 UTC, amitbhatt818 approved these changes
/lgtm

2020-06-26 07:14 UTC, merged